"""Add mpesa_confirmation to hire_requests

Revision ID: 36a1b59e20ab
Revises: 7b1d24bc835d
Create Date: 2026-03-27 13:49:42.089956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a1b59e20ab'
down_revision = '7b1d24bc835d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hire_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_confirmation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hire_requests', schema=None) as batch_op:
        batch_op.drop_column('mpesa_confirmation')

    # ### end Alembic commands ###
