"""Add whatsapp_number to hire_requests

Revision ID: 3810f38821ff
Revises: 36a1b59e20ab
Create Date: 2026-03-27 15:59:29.093890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3810f38821ff'
down_revision = '36a1b59e20ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hire_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hire_requests', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_number')

    # ### end Alembic commands ###
