"""Add category notes project_id to pm_expenses

Revision ID: 54d2d5981e5c
Revises: 3810f38821ff
Create Date: 2026-03-27 16:24:07.772368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d2d5981e5c'
down_revision = '3810f38821ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pm_expenses_project_id', 'pm_projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm_expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pm_expenses_project_id', type_='foreignkey')
        batch_op.drop_column('project_id')
        batch_op.drop_column('notes')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
