"""Add payment_status to hire_requests

Revision ID: 5c1b75944b9d
Revises: 6fbe727f77d6
Create Date: 2026-03-27 12:45:02.289571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1b75944b9d'
down_revision = '6fbe727f77d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hire_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hire_requests', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
