"""Add Invoice model and NDA/invoice fields to HireRequest

Revision ID: 7b1d24bc835d
Revises: 5c1b75944b9d
Create Date: 2026-03-27 13:16:30.081662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1d24bc835d'
down_revision = '5c1b75944b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hire_request_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_type', sa.String(length=20), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hire_request_id'], ['hire_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    with op.batch_alter_table('hire_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nda_signed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('invoice_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('invoice_opt_out', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hire_requests', schema=None) as batch_op:
        batch_op.drop_column('invoice_opt_out')
        batch_op.drop_column('invoice_email')
        batch_op.drop_column('nda_signed')

    op.drop_table('invoices')
    # ### end Alembic commands ###
